### ISSUE TITLE
Enable debug_traceBlockByNumber

### ISSUE THREAD

**Issue by DylanCkawalec** [GOATNetwork/go-ethereum#6]
#### System information

Geth version: `geth version`
CL client & version: e.g. lighthouse/nimbus/prysm@v1.0.0
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Expected behaviour
Data On request 

#### Actual behaviour
Error, returns null 

#### Steps to reproduce the behaviour
Run debug_traceBlockByNumber JRPC and it will result in a 404, or invalid input depending on the POST data sync/structure.

**Comment by ericlee42** [comment]
You need to have --gcmode archive and --http.api debug to enable the api 

Check out the regtest repository for the details
